/*Desafio: número de notas salvas em uma tabela*/

IF OBJECT_ID('TABELANOTAS','U') IS NOT NULL DROP TABLE TABELANOTAS
CREATE TABLE TABELANOTAS (DATA DATE, NUMNOTAS INT)

DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT

SET @DATAINICIAL = '2017-01-01'
SET @DATAFINAL = '2017-01-10'

WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL
    INSERT INTO TABELANOTAS (DATA, NUMNOTAS) 
        VALUES (@DATAINICIAL, @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END

SELECT * FROM TABELANOTAS