/*Desafio: número de notas para diversos dias*/
DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT

SET @DATAINICIAL = '2017-01-01'
SET @DATAFINAL = '2017-01-10'

WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
	SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATAINICIAL
    PRINT 'DIA: ' + CONVERT(VARCHAR(10), @DATAINICIAL) + ' - NOTAS: ' + CONVERT(VARCHAR(10), @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END