/*Desafio: fazendo o UPDATE apenas se necessário*/
DECLARE @CPF VARCHAR(15)
DECLARE @DATA_NASCIMENTO DATE
DECLARE @IDADE INT
DECLARE @IDADE_ATUAL INT

SET @CPF = '1471156710'
SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE_ATUAL = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE())
IF @IDADE_ATUAL <> @IDADE UPDATE [TABELA DE CLIENTES] SET IDADE = @IDADE WHERE CPF = @CPF
	