/*Desafio: usando o SELECT no IF*/
DECLARE @CPF VARCHAR(15)
DECLARE @DATA_NASCIMENTO DATE
DECLARE @IDADE INT

SET @CPF = '1471156710'

SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES] WHERE CPF = @CPF

SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE())

IF (SELECT COUNT(*) FROM  [TABELA DE CLIENTES] WHERE CPF = @CPF AND IDADE <> @IDADE) = 1 
    UPDATE [TABELA DE CLIENTES] SET IDADE = @IDADE WHERE CPF = @CPF